/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:0bc556be-5bac-4fd0-b102-78d61339fd6b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_eaV1gT0Qu",
    "aws_user_pools_web_client_id": "ogtsc27pohekbte38no9m3ck4",
    "oauth": {},
    "aws_user_files_s3_bucket": "thebyteappcdc68999fdd2490fac9903262d2f285d103333-prod",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://ehlsdsxdw5albmqsoatkr3sazq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-7ei476ocdfbczme6o3jgodho4q",
    "aws_content_delivery_bucket": "thebyteapp-20201129204728-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://thebyteapp-20201129204728-hostingbucket-prod.s3-website.eu-west-2.amazonaws.com"
};


export default awsmobile;
